worker_processes auto;

events { 
    worker_connections 1024;
}

http {

    geo $proxy {
        default          0;
        172.18.0.1       0;
        172.18.0.0/24    1;
    }

    map $proxy $x_forwarded_for_value {
        0    "$remote_addr";
        1    "$http_x_forwarded_for, $remote_addr";       
    }   

    include /etc/nginx/conf.d/*.conf;
}
